require('dotenv').config();
const bcrypt = require('bcryptjs');
const mysqlOrm = require('mysql-orm');

const User = require('../models/User');
const School = require('../models/School');
const Grade = require('../models/Grade');
const Topic = require('../models/Topic');
const SubTopic = require('../models/SubTopic');
const GroupTag = require('../models/GroupTag');
const AssignedTutors = require('../models/AssignedTutors');
const TutorAvailability = require('../models/TutorAvailability');
const TutorPreference = require('../models/TutorPreference');
const StudentPreference = require('../models/StudentPreference');
const PointSystem = require('../models/PointSystem');
const PointBalance = require('../models/PointBalance');
const Voucher = require('../models/Voucher');
const EventCategory = require('../models/EventCategory');
const EventLocation = require('../models/EventLocation');
const Event = require('../models/Event');
const ChargeCategory = require('../models/ChargeCategory');
const Transaction = require('../models/Transaction');
const Invoice = require('../models/Invoice');
const Policy = require('../models/Policy');
const BusinessSetting = require('../models/BusinessSetting');
const LearningContent = require('../models/LearningContent');
const Lesson = require('../models/Lesson');
const Slide = require('../models/Slide');
const Practice = require('../models/Practice');
const Challenge = require('../models/Challenge');
const Program = require('../models/Program');
const Assessment = require('../models/Assessment');

const DEMO_PASSWORD = 'Password@123';

async function findOrCreate(Model, filter, values, stats) {
  const existing = await Model.findOne(filter);
  if (existing) {
    stats.reused++;
    return existing;
  }
  const created = await Model.create(values);
  stats.created++;
  return created;
}

function futureDate(days, hour = 10, minute = 0) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, minute, 0, 0);
  return date;
}

async function seedDatabase() {
  await mysqlOrm.connect();
  const stats = { created: 0, reused: 0 };
  const password = await bcrypt.hash(DEMO_PASSWORD, 10);

  const school = await findOrCreate(School, { name: 'Demo Learning Academy' }, {
    name: 'Demo Learning Academy', email: 'school@demo.local', dial_code: 61,
    iso_code: 'AU', phone: '0290000000', address: '100 Education Street, Sydney NSW', status: 1,
  }, stats);
  const grade = await findOrCreate(Grade, { name: 'Demo Grade 6' }, { name: 'Demo Grade 6', status: 1 }, stats);
  const topic = await findOrCreate(Topic, { name: 'Demo Mathematics' }, {
    name: 'Demo Mathematics', note: 'Mathematics concepts and practical exercises.', status: 1,
  }, stats);
  const subTopic = await findOrCreate(SubTopic, { name: 'Demo Fractions' }, {
    name: 'Demo Fractions', topic_id: topic._id, note: 'Fractions, decimals and percentages.', status: 1,
  }, stats);

  const admin = await findOrCreate(User, { email: 'admin@demo.local' }, {
    role: 1, username: 'demo_admin', first_name: 'Demo', last_name: 'Administrator',
    email: 'admin@demo.local', password, phone: '0400000001', status: 1, time_zone: 'Australia/Sydney',
  }, stats);
  const tutor = await findOrCreate(User, { email: 'tutor@demo.local' }, {
    role: 2, username: 'demo_tutor', first_name: 'Taylor', last_name: 'Tutor',
    email: 'tutor@demo.local', password, phone: '0400000002', status: 1,
    time_zone: 'Australia/Sydney', qualification: 'Bachelor of Education', calendar_color: '#4f46e5',
    subject_ids: [topic._id], virtual_meeting_link: 'https://meet.example.test/demo-class',
  }, stats);
  const student = await findOrCreate(User, { email: 'student@demo.local' }, {
    role: 3, username: 'demo_student', first_name: 'Sam', last_name: 'Student',
    email: 'student@demo.local', password, phone: '0400000003', status: 1,
    time_zone: 'Australia/Sydney', grade_id: grade._id, school_id: school._id,
    birth_day: new Date('2013-05-15'), address: '20 Sample Avenue, Sydney NSW', auto_invoice: true,
  }, stats);
  await findOrCreate(User, { email: 'content@demo.local' }, {
    role: 4, username: 'demo_content', first_name: 'Casey', last_name: 'Content Manager',
    email: 'content@demo.local', password, phone: '0400000004', status: 1, time_zone: 'Australia/Sydney',
  }, stats);

  const tag = await findOrCreate(GroupTag, { name: 'Demo Students' }, {
    name: 'Demo Students', student_ids: [student._id], created_by: admin._id,
    color: 'blue', description: 'Students generated by the demo seeder.', active_status: true,
  }, stats);
  const wallet = await findOrCreate(PointBalance, { userId: student._id }, { userId: student._id, balance: 125 }, stats);
  await User.updateOne({ _id: student._id }, { $set: { group_tag_id: tag._id, points_wallet_id: wallet._id } });

  await findOrCreate(AssignedTutors, { student_id: student._id, tutor_id: tutor._id }, {
    student_id: student._id, tutor_id: tutor._id, default_lesson_category: 'lesson',
    default_duration: '60', price: 65, default_billing: 'hourly',
  }, stats);
  const availability = await findOrCreate(TutorAvailability, { tutor_id: tutor._id }, {
    tutor_id: tutor._id, days: ['monday', 'tuesday', 'wednesday', 'thursday'],
    start_date_time: 540, end_date_time: 1020, note: 'Demo weekday availability', isApproved: '1',
  }, stats);
  await User.updateOne({ _id: tutor._id }, { $addToSet: { availability_id: availability._id } });
  await findOrCreate(TutorPreference, { tutor_id: tutor._id }, {
    tutor_id: tutor._id, email_notification_preferences: [{
      register_for_lesson: true, cancel_for_lesson: true, email_daily_agenda: 'daily',
      select_time: '07:00', send_email_daily_agenda: true,
    }],
  }, stats);
  await findOrCreate(StudentPreference, { student_id: student._id }, {
    student_id: student._id, title: 'Parent', first_name: 'Alex', last_name: 'Student',
    mobile_number: [{ number: '0400000010', is_sms_capable: true }], email: 'parent@demo.local',
    address: '20 Sample Avenue, Sydney NSW', preferences: [{
      preferred_invoice_recipient: true, student_portal_contact: true,
      email_lesson_reminders: true, sms_lesson_reminders: true,
    }],
  }, stats);

  await findOrCreate(PointSystem, {}, {
    attendingClassOnTime: 5, askingQuestions: 10, homeworkSubmission: 10,
    participatingClassActivities: 5, bonusPoints: 10, assignmentGapDuration: 1,
    redemptionGapDuration: 13, pointAssignmentModificationPeriod: 5,
  }, stats);
  await findOrCreate(Voucher, { title: 'Demo $10 Learning Voucher' }, {
    title: 'Demo $10 Learning Voucher', required_points: 100, equivalent_amount: 10,
  }, stats);

  const category = await findOrCreate(EventCategory, { name: 'Demo Lesson' }, {
    name: 'Demo Lesson', color: '#4f46e5', email_reminder: '24 hours', sms_reminder: '2 hours',
  }, stats);
  const location = await findOrCreate(EventLocation, { name: 'Demo Online Classroom' }, {
    name: 'Demo Online Classroom', color: '#0ea5e9', icons: 'fa-video', location_type: 'online',
    specific_address_details: 'Use the meeting link in the lesson details.',
  }, stats);
  const event = await findOrCreate(Event, { public_note: 'Demo lesson generated by the fake seeder.' }, {
    tutor_id: tutor._id, student_ids: [student._id], event_category_id: category._id,
    event_location_id: location._id, start_date: futureDate(1, 16), start_time: futureDate(1, 16),
    end_time: futureDate(1, 17), duration: '60', public_note: 'Demo lesson generated by the fake seeder.',
    private_note: 'Safe sample data only.', status: 'Processing', will_repeat: false,
    student_pricing_option: 'std_price_specify', per_std_lesson_price: 65,
  }, stats);

  const chargeCategory = await findOrCreate(ChargeCategory, { name: 'Demo Tuition Fee' }, { name: 'Demo Tuition Fee' }, stats);
  const transaction = await findOrCreate(Transaction, { note: 'Demo lesson charge' }, {
    type: 'Charge', student_id: student._id, event_id: event._id, date: new Date(), amount: 65,
    note: 'Demo lesson charge', charge_type: 'student', category: { kind: 'charge', refId: chargeCategory._id },
    recurring: false, created_by: admin._id,
  }, stats);
  await findOrCreate(Invoice, { invoice_number: 'DEMO-0001' }, {
    student_id: student._id, transactions: [{
      type: transaction.type, date: transaction.date, amount: transaction.amount, note: transaction.note,
      student_id: student._id, event_id: event._id, category: { kind: 'charge', refId: chargeCategory._id },
    }], invoice_number: 'DEMO-0001', invoice_amount: 65, paid_amount: 0, created_by: admin._id,
    date: new Date(), include_balance_type: 'charges', category: [chargeCategory._id], previous_balance: 0,
    total_payments: 0, total_charges: 65, date_range: { start: new Date(), end: futureDate(7) },
    due_date: futureDate(14), display_type: 'normal', footer_note: 'Thank you for learning with us.',
    private_note: 'Demo invoice', is_paid: false,
  }, stats);

  const slide = await findOrCreate(Slide, { title: 'Demo Understanding Fractions' }, {
    title: 'Demo Understanding Fractions', duration: '10',
    description: 'Introduction to numerators and denominators.', position: 1,
  }, stats);
  const practice = await findOrCreate(Practice, { question_title: 'Demo Fraction Practice' }, {
    question_type: 'selectText', question_title: 'Demo Fraction Practice',
    question: 'Which fraction represents one half?', question_duration: '5',
    question_explanation: 'One out of two equal parts is one half.', position: 1,
    options: [{ option_text: '1/2', option_correct: true }, { option_text: '1/3', option_correct: false }],
  }, stats);
  const challenge = await findOrCreate(Challenge, { title: 'Demo Multiplication Warm-up' }, {
    title: 'Demo Multiplication Warm-up', type: 'multiplication', duration: '5',
    show_timer: true, practice_ids: [practice._id], multiplication_no: 6, position: 1,
  }, stats);
  const lesson = await findOrCreate(Lesson, { title: 'Demo Fractions Fundamentals' }, {
    title: 'Demo Fractions Fundamentals', slide_ids: [slide._id], practice_ids: [practice._id],
    challenge_ids: [challenge._id], position: 1,
  }, stats);
  const content = await findOrCreate(LearningContent, { title: 'Demo Grade 6 Mathematics' }, {
    grade_id: grade._id, topic_id: topic._id, sub_topic_id: subTopic._id,
    title: 'Demo Grade 6 Mathematics', short_description: 'A complete sample learning module.',
    content_directory: 'demo-grade-6-mathematics', lesson_ids: [lesson._id], status: 1,
  }, stats);
  await findOrCreate(Program, { name: 'Demo Mathematics Program' }, {
    name: 'Demo Mathematics Program', status: 'Active', percentage: 25,
    ex_content: [{ lesson_id: lesson._id, learning_content_id: content._id, slides: [slide._id], is_skipped: false }],
  }, stats);
  await findOrCreate(Assessment, { name: 'Demo Fractions Assessment' }, {
    name: 'Demo Fractions Assessment', apply_duration: true, task_types: ['practice'],
    tutor_id: tutor._id, student_ids: [student._id], status: 'Active', date: futureDate(3).toISOString(),
    content: [{ learning_content_id: content._id, lessons: [{
      lesson_id: lesson._id, practice_ids: [practice._id], challenges_ids: [challenge._id],
    }] }],
  }, stats);

  await findOrCreate(Policy, { title: 'Demo Attendance and Cancellation Policy' }, {
    title: 'Demo Attendance and Cancellation Policy', status: 1, marked_as_read: [],
  }, stats);
  await findOrCreate(BusinessSetting, { primary_email: 'admin@demo.local' }, {
    name: 'Tutor Hub Demo', primary_number: 290000000, primary_email: 'admin@demo.local',
    notification_settings: [{ send_birthday_email: true }], event_scheduling: [{ check_scheduling_conflict: true }],
    cancellation_policy: [{ allow_event_cancellation: true, prior_cancellation_time: 24,
      notify_on_cancellation: true, policy_text: 'Please provide at least 24 hours notice.' }],
    sales_taxes: [{ _id: new mysqlOrm.Types.ObjectId(), tax_name: 'GST', tax_rate: 10, is_default: true }],
    family_contact_settings: [{ payment_methods: [
      { _id: new mysqlOrm.Types.ObjectId(), method: 'Bank Transfer' },
      { _id: new mysqlOrm.Types.ObjectId(), method: 'Card' },
    ], balance_date_type: 'current' }],
  }, stats);

  console.log(`Fake seeder complete: ${stats.created} created, ${stats.reused} reused.`);
  console.log('Demo logins (all use Password@123):');
  console.log('  Admin: admin@demo.local');
  console.log('  Tutor: tutor@demo.local');
  console.log('  Student: student@demo.local');
  console.log('  Content Manager: content@demo.local');
  return stats;
}

if (require.main === module) {
  seedDatabase()
    .then(() => mysqlOrm.connection.close())
    .catch(async (error) => {
      console.error('Fake seeder failed:', error);
      await mysqlOrm.connection.close().catch(() => {});
      process.exitCode = 1;
    });
}

module.exports = seedDatabase;
