module.exports = {
  numberOfRecurringEvents: 5,
  tutorPayrollTypes: [
    // { key: 'no_auto_calc', label: "No automatic payroll calculation" },
    // { key: 'revenue_percentage', label: "Total of Revenue Percentage" },
    { key: 'hourly_rate', label: "Per Hour Rate" },
  ],
  defaultTutorDuration: 60,
  currency: {
    'symbol': '$',
    'name': 'USD',
    'icon':'fa fa-dollar',
  },
  lessonCategory: [
    { key: 'group_lesson', label: 'Group Lesson'},
    { key: 'lesson', label: 'Lesson'},
    { key: 'vacation', label: 'Vacation'},
  ],
  recurringFrequency : [
    { val: 'daily', label: "Daily"},
    { val: 'weekly', label: "Weekly"},
    { val: 'monthly', label: "Monthly"},
    { val: 'yearly', label: "Yearly"},
  ],
  repeatDays : [
    { val: 'sunday', label: "Sun"},
    { val: 'monday', label: "Mon"},
    { val: 'tuesday', label: "Tue"},
    { val: 'wednesday', label: "Wed"},
    { val: 'thursday', label: "Thu"},
    { val: 'friday', label: "Fri"},
    { val: 'saturday', label: "Sat"},
  ],
  invoice_types : [
    { val: 'condensed', label: "Condensed", default: false, description: 'Combine identical items into a single line.', img:'format-condensed.svg'},
    { val: 'normal', label: "Normal", default: true, description: 'Show each lesson / event on its own line', img:'format-normal.svg'},
    { val: 'expanded', label: "Expanded", default: false, description: 'Include lessons / events with no charges', img:'format-expanded.svg'},
  ],
  transactionTypes: [
    { type: 'Payment', desc: 'Use when a family pays you money.' },
    { type: 'Refund', desc: 'Use when you physically give money back to a family.' },
    { type: 'Charge', desc: 'Increase what a family owes without receiving money.' },
    { type: 'Discount', desc: 'Reduce what a family owes without receiving money.' }
  ],
  tag_colors: [
    { key:'beach', label: 'Beach', background_color:'#faf0e6', color: '#743a00' },
    { key:'brown',label: 'Brown', background_color:'#d0ab8b', color: '#4f2700' },
    { key:'grass_green', label: 'Grass Green', background_color:'#c8decd', color: '#004a34' },
    { key:'dark_orange', label: 'Dark Orange', background_color:'#ffd2b9', color: '#aa3000' },
    { key:'grey', label: 'Grey', background_color:'#e4e4e4', color: '#434444' },
    { key:'green', label: 'Green', background_color:'#e4efe9', color: '#344242' },
    { key:'lavender', label: 'Lavender', background_color:'#d6cbf0', color: '#604274' },
    { key:'light_grey', label: 'Light Grey', background_color:'#f8f8f8', color: '#424e5b' },
    { key:'light_pink', label: 'Light Pink', background_color:'#fff0f3', color: '#9b0027' },
    { key:'lime', label: 'Lime', background_color:'#d9f1bb', color: '#004a34' },
    { key:'magenta', label: 'Magenta', background_color:'#ffddfc', color: '#b92e71' },
    { key:'mint', label: 'Mint',background_color:'#c5f5f1',  color: '#005c5c' },
    { key:'olive', label: 'Olive', background_color:'#dedebe', color: '#313216' },
    { key:'orange', label: 'Orange', background_color:'#ffdcb3', color: '#d43c00' },
    { key:'pink', label: 'Pink', background_color:'#ffe2f0', color: '#c6003b' },
    { key:'purple', label: 'Purple', background_color:'#f9e5ff', color: '#604274' },
    { key:'red', label: 'Red', background_color:'#ffe4e4', color: '#cc0019' },
    { key:'royal', label: 'Royal', background_color:'#c3d1e5', color: '#0c3369' },
    { key:'ruby', label: 'Ruby', background_color:'#fdc9dc', color: '#940237' },
    { key:'salmon', label: 'Salmon', background_color:'#ffece8', color: '#c33700' },
    { key:'blue', label: 'Blue', background_color:'#afe9f8', color: '#2e568e' },
    { key:'sea_blue', label: 'Sea Blue', background_color:'#e5f5f9', color: '#006f8f' },
    { key:'tan', label: 'Tan', background_color:'#efcdaf', color: '#4f2700' },
    { key:'tangerine', label: 'Tangerine',background_color:'#fff1d7', color: '#e34c00' },
    { key:'teal', label: 'Teal',background_color:'#c9e4e4', color: '#005c5c' },
    { key:'white', label: 'White',background_color:'#ffffff', color: '#434444' },
    { key:'yellow', label: 'Yellow',background_color:'#ffffc4', color: '#743a00' },
  ],
  
};